---
title: "HealthEconA1"
author: "Mathijs Lenderink"
date: "`r Sys.Date()`"
output: pdf_document
---





```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(ggrepel)
#library(brms)
library(tidybayes)
```


```{r}

cc <- read.csv("Data/cc.csv") %>% 
  select(Country, Year, Function, Value) %>%
   spread(Function, Value) %>%
  na.omit() %>%
  rename(CR = `Curative and rehabilitative care`, AS = `Ancillary services (non-specified by function)`,
         MG = `Medical goods (non-specified by function)`) %>%
  mutate(cc = CR + MG + AS) %>%
  select(country = Country, year = Year, cc)

gdp <- read.csv("Data/gdp.csv") %>%
  select(country = Country, year = Year, gdp = Value) 

le <- read.csv("Data/le.csv")%>%
   select(country = Country, year = Year, le = Value) 

pop <- read.csv("Data/pop.csv") %>%
  select(country = Country, year = Year, population = Value)

HEpc <- read.csv("Data/HEpercapita.csv") %>%
  select(country = Country, year = Year, HEpc = Value)

oecd1 <- full_join(HEpc, gdp, by = c("country", "year"))
oecd2 <- full_join(oecd1, le, by = c("country", "year")) 

oecd <- full_join(oecd2, pop, by = c("country", "year"))%>%
  na.omit()

oecd$year <- as.factor(oecd$year)
```

```{r}
df <- filter(oecd, year == 2016)
countries <- unique(oecd$country)
EUcountries <- list("Austria","Belgium","Bulgaria","Croatia" ,"Cyprus" ,"Czech Republic","Denmark","Estonia",         "Finland","France","Germany","Greece" , "Hungary" ,"Iceland","Ireland","Italy","Latvia","Lithuania","Luxembourg","Netherlands", "Poland","Portugal", "Romania" ,"Slovak Republic" ,"Slovenia" , "Spain", "Sweden",  "United Kingdom" )

EUdf <- filter(df, country %in% EUcountries)


```

```{r}
HEnl <- EUdf$HEpc[EUdf$country == "Netherlands"]

ggplot(data = EUdf, aes(x = HEpc, y = le, label = country))+
  geom_point(color = "blue")+
  geom_text(nudge_y = 0.3, size = 2)+
  labs(x = "Health Expenditure per capita", y = "Life Expectancy at birth")+
  geom_segment(aes(x = HEnl,
                   y = le,
                   yend = le,
                   xend = HEpc),
               color = 'darkgreen')+
  geom_vline(xintercept = HEnl, color = "black", linetype = "longdash")

```



